Neos:
  Neos:
    Ui:
      frontendConfiguration:
        'Lala.ListStyle:Styles': '${Configuration.setting("Lala.ListStyle.styles")}'

      resources:
        javascript:
          'Lala.ListStyle:Plugin':
            resource: resource://Lala.ListStyle/Public/Plugin.js
        stylesheets:
          'Lala.ListStyle:Plugin':
            resource: resource://Lala.ListStyle/Public/Plugin.css
